### ISSUE TITLE
Possible to get permanently stuck in Crashed Frigate

### ISSUE THREAD

**Issue by Touchebag** [EthanArmbrust/new-prime-seed-generator#2]
Getting Gravity Suit before Space Jump makes it possible to soft lock a save file in the Crashed Frigate.

You will not be able to progress past the Cargo Freight Lift and you also require the Space Jump to get out via the Main Ventilation Shaft.

As the easy difficulty does not require any glitches you can get permanently stuck if you save at the save station at Reactor Access.

A suggestion would be to change the logic to require Space Jump before you can get Gravity Suit. At least on easy though I am not aware of any specific glitch that would be able to save this situation.

My full item list at that point:
Misssiles
Morph Ball
Gravity Suit
Wave Beam
Ice Beam
Thermal Visor
X-Ray Visor

**Comment by EthanArmbrust** [comment]
This is kind of outside of the scope of the project. The seed gen picks seeds that have a completable path, but it can't prevent you from taking a wrong path that will softlock the game. Seeing as how the seed generator doesn't actually modify the game in anyway (that's the actual randomizers job) there's nothing I can really do to stop a player from locking themselves in the crashed frigate.  

If the seed was requiring you to go into the crashed frigate without space jump to pick up a needed item, give me the seed number and list of excluded items and I'll look into it.

**Comment by Touchebag** [comment]
No, the seed was not forcing me to go in there. I simply thought it was worth mentioning since while you can get stuck in other places (Incinerator Drone not giving bombs for instance) this actually has a save point where you could bork that file permanently.

As I suggested you can change the "beatable" logic to make this situation impossible but I can also see why it would be outside the scope so never mind.
